# Change these first
owner: tmrw-health # Your GitHub organization or username, where this repository lives
repo: tmrw-status-page # The name of this repository

sites:
  - name: Member App
    url: https://app.startmytomorrow.com/
  - name: API
    url: https://api.core.startmytomorrow.com/health-check

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.startmytomorrow.com
  # baseUrl: /tmrw-status-page
  logoUrl: https://www.startmytomorrow.com/design/tmrw_icon_main.png
  name: TMRW Status
  introTitle: "**TMRW** system status"
  introMessage: Live status and incident history for TMRW's app and API.
  navbar:
    - title: Status
      href: /
    - title: TMRW
      href: https://www.startmytomorrow.com
  theme: light
  css: |
    :root {
      --nav-current-border-bottom-color: #500000;
      --up-border-left-color: #500000;
      --tag-up-background-color: #05a52a;
      --down-border-left-color: #ef4444;
      --tag-down-background-color: #ef4444;
      --degraded-border-left-color: #d1ab00;
      --tag-degraded-background-color: #d1ab00;
      --graph-filter: hue-rotate(-155deg) saturate(1.4) brightness(0.65);
    }

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
